version: '3.9'
services:
  web:
    image: garrobo0/pruebafinal:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - 443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pruebafinal?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pruebafinal
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      retries: 5


